version: '3.2'

services:
  nginx:
    image: nginx:1.17-alpine
    container_name: '${PROJECT_NAME}_nginx'
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '${FORWARD_APP_PORT:-80}:80'
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
      - ./data/nginx:/var/log/nginx
    networks:
      - bittracker
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        UID: '${UID}'
        GID: '${GID}'
    container_name: '${PROJECT_NAME}_app'
    restart: always
    env_file:
      - .env
    volumes:
      - "./app:/var/www/html"
    depends_on:
      - db
      - nginx
    networks:
      - bittracker
  db:
    image: postgres:14.7-alpine
    container_name: '${PROJECT_NAME}_db'
    volumes:
      - ./data/db:/var/lib/postgresql/data
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
    ports:
      - '${FORWARD_DB_PORT}:${FORWARD_DB_PORT}'
    networks:
      - bittracker
networks:
  bittracker:
    driver: bridge